name: 7stest
favicon: null
layout_spectrum: 0.58361
typography_spectrum: 0.97705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#232323'
    - '#9a9a9a'
    - '#4c4c4c'
    - '#777777'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
